Repository Mizerski/ProjectDiet, pull requests merged in 2023-12, with the labels that each got.

#11 Many fixes
  .eslintrc.cjs
  App.tsx
  __test__/translations.test.js
  coverage/clover.xml
  coverage/lcov-report/index.html
  package.json
  src/Components/Dropdown/index.tsx
  src/Pages/Settings/index.tsx
  src/i18n/json/pt-BR.json
Labels: improvement

#13 Impl storage
  .gitignore
  App.tsx
  __test__/storage.test.js
  __test__/translations.test.js
  app.json
  coverage/clover.xml
  coverage/lcov-report/index.html
  package-lock.json
  package.json
  src/Components/Dropdown/index.tsx
  src/Constants/DropdownItems.ts
  src/Hooks/Languages.ts
  src/Pages/Settings/index.tsx
  src/i18n/index.ts
  src/i18n/json/en-US.json
  src/i18n/json/es-ES.json
  src/i18n/json/pt-BR.json
Labels: enhancement, improvement

#17 New pre-commit
  .husky/pre-commit
  coverage/clover.xml
  coverage/lcov-report/index.html
Labels: enhancement

#18 Login screen
  App.tsx
  coverage/clover.xml
  coverage/lcov-report/index.html
  mock/db/user.ts
  package-lock.json
  package.json
  src/Constants/Regex.ts
  src/Pages/Login/index.tsx
  tsconfig.json
Labels: enhancement

#27 Login buttons
  App.tsx
  __test__/translations.test.js
  app.json
  assets/styles/Colors.ts
  assets/styles/Compontes.ts
  index.js
  package-lock.json
  package.json
  setupConsole.js
  src/Classes/Form.ts
  src/Components/Buttons/ButtonLoading.tsx
  src/Components/Forms/Base/BaseFormField.tsx
  src/Components/Forms/FormContainer.tsx
  src/Components/Forms/TextField.tsx
  src/Components/Inputs/InputField.tsx
  src/Constants/Regex.ts
  src/Database/Storage/index.ts
  src/Hooks/Languages.ts
  src/Interface/User.ts
  src/Pages/Home/index.tsx
  src/Pages/Login/LoginForm.ts
  src/Pages/Login/index.tsx
  src/Routes/root.routes.tsx
  src/i18n/Languages.ts
  src/i18n/index.ts
  src/i18n/json/en.json
  src/i18n/json/es-ES.json
  src/i18n/json/es.json
  src/i18n/json/pt.json
  tsconfig.json
Labels: improvement
